### ISSUE TITLE
Add more words

### ISSUE THREAD

**Issue by srbmaury** [srbmaury/dictionary#2]
It's funny but currently, it has 4306 words. Don't use API. Let it be beginner-friendly.

**Comment by clydehenry3** [comment]
Hi! I saw your project and would love to help. Would you like to add slang to this or just simple single word translation?

**Comment by srbmaury** [comment]
You may add anything genuine.

**Comment by clydehenry3** [comment]
Great. I will get right on this. Thank you for this project.

**Comment by srbmaury** [comment]
Hey @clydehenry3 are you working on this?

**Comment by clydehenry3** [comment]
Yes! Working on this today. I got sick over the past two days. When I put words in, I need to put them alphabetically correct? Or is there something that automatically organizes them. Looking to add lots of words today.

**Comment by srbmaury** [comment]
If you can add something which automatically organises words in
alphabetical order or just run some code and after sorting include in this
code. I believe currently there is no sorting technology implemented.

**Comment by clydehenry3** [comment]
Got it. I think I may have found a way for some JS to take care of this for us.

**Comment by clydehenry3** [comment]
@srbmaury I just noticed that the repo has a type for hacktoberfest and isn't considered to be a participating repo. Could you add this to the repo for hacktoberfest participation? Thanks!
