### ISSUE TITLE
Change Link

### ISSUE THREAD

**Issue by srbmaury** [srbmaury/dictionary#3]
Redirect my all projects link to https://github.com/srbmaury?tab=repositories

**Comment by ayushsgithub** [comment]
@srbmaury From where do you want to redirect?

**Comment by srbmaury** [comment]
> @srbmaury From where do you want to redirect?

In UI there is an invalid link. Check at https://srbmaury.github.io/dictionary/

**Comment by lovbackan** [comment]
I can do it if you still need it done :)
